### ISSUE TITLE
default-directory set to project root after venv-workon

### ISSUE THREAD

**Issue by julienfantin** [porterjamesj/virtualenvwrapper.el#65] opened 2018-07-31 18:14 UTC
Using the version from MELPA, after I activate an environment with `venv-workon` the `default-directory` is set to the project root in all opened project buffers, this makes it difficult to use this function in a hook since.

**Comment by galeo** [comment] 2018-09-30 03:47
Now it is confirmed that `venv--switch-to-project-dir` in `venv--activate-dir` causes the problem. When invode `venv-workon`, it will call `venv--activate-dir` and then `venv--switch-to-project-dir` is called.

```elisp
(defun venv--switch-to-project-dir ()
  "If we find the project file, cd into that directory"
  (let ((proj-file (expand-file-name ".project" venv-current-dir)))
    (when (file-exists-p proj-file)
      (cd (with-temp-buffer
            (insert-file-contents proj-file)
            (string-trim (buffer-string)))))))
```

If there is a `.project` file in `venv-current-dir`, it will try to switch to the directory which is the project path the `.project` file contains.

As the `cd` function doc string shows that, it will change the default directory of the opened directory buffers to the project root directory.

It seems that the latest version of [pipenv](https://github.com/pypa/pipenv) will create the `.project` file in the initialization of an virtual environment.

**Comment by julienfantin** [comment] 2018-11-03 18:58
Ah correct, most of the code that currently uses 
```emacs-lisp
(cd venv-current-dir)
...forms...
```

Should instead create a lexical scope for `default-directory`

```emacs-lisp
(let ((default-directory venv-current-dir))
  ...forms...)
```

**Comment by kaiwk** [comment] 2019-01-08 04:20
I had this problem too. At first time, I thought it was `.dir-locals.el`.

.dir-locals.el:
``` elisp
((python-mode
  (eval . (venv-workon "myproject"))
  (flycheck-checker . python-pylint)))
```

Finally, I found it was caused by `venv-workon`, somehow it changed `default-directory`, and `find-file` always use project root as prompt prefix.

So I add this to my emacs config:
``` elisp
(add-hook 'venv-postactivate-hook (lambda ()
                                    (setq default-directory
                                          (file-name-directory (buffer-file-name)))))
```

**Comment by porterjamesj** [comment] 2019-01-19 00:40
Hi folks, sorry for the (very) long reply here.

This behavior is as intended—I try to make the behavior of this project mirror that of the original virtualenvwrapper wherever possible, and moving to the project directory when a virtualenv is activated is what virtualenvwrapper does, so I'm going to keep it that way too. That said, virtualenvwrapper has [an option to turn this off](https://virtualenvwrapper.readthedocs.io/en/latest/install.html#enable-project-directory-switching), which I hadn't implemented, but I've just made a PR for.

If one of you can try [this PR](https://github.com/porterjamesj/virtualenvwrapper.el/pull/66) and confirm that setting `venv-workon-cd` to `nil` fixes the issue for you, I'll merge it and close this issue. Thanks!

**Comment by kaiwk** [comment] 2019-01-19 12:03
It works for me, thank you!

**Comment by porterjamesj** [comment] 2019-01-23 16:44
Great, thank you!

**Closed** 2019-01-23 16:45 UTC
